<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Group extends Model
{
    use HasFactory;

    protected $hidden = ['updated_at'];

    protected $guarded = ['id'];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function interests()
    {
        return $this->morphToMany(Interest::class, 'interestables');
    }

    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub

        $isJoined = DB::table('group_user')->where('group_id', $data['id'])
                      ->where('user_id', Auth::id())->first();
        if ($isJoined) {
            $data['is_joined'] = true;
        } else {
            $data['is_joined'] = false;
        }


        return $data;
    }
}
